trace-cmd: update to 2.4.2
fixes compile error:
(observed w. target arm64, all kernel build opts enabled)
error: call to '__open_missing_mode' declared with attribute
error: open with O_CREAT in second argument needs 3 arguments

Signed-off-by: Dirk Neukirchen <dirkneukirchen@web.de>

SVN-Revision: 45625